- hosts: web
  sudo: yes
  remote_user: vagrant

  tasks:
    # This should work too / #2372
    # - name: Pushes user key to root's on vagrant boxes
    #   action: authorized_key key=$FILE($item) user=root
    #   first_available_file:
    #     - ~/.ssh/id_dsa.pub
    #     - ~/.ssh/id_rsa.pub

    - name: Creates destination directory
      file: state=directory mode=0700 dest=/root/.ssh/
      register: file_op

    - name: Pushes user's rsa key to root's vagrant box (it's ok if this TASK fails)
      copy: src=~/.ssh/id_rsa.pub dest=/root/.ssh/authorized_keys owner=root mode=0600
      register: rsa
      ignore_errors: yes

    - name: Pushes user's dsa key to root's vagrant box (it's NOT ok if both TASKs fail)
      copy: src=~/.ssh/id_dsa.pub dest=/root/.ssh/authorized_keys owner=root mode=0600
      when: rsa|failed

    - name: Checks if resolver is working properly (issues with some VBox/Host OS combinations)
      command: host -t A ansible.cc
      register: ns
      ignore_errors: yes
